# Use the Node.js image for the build stage
FROM node:alpine AS build

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm install

# Copy the entire project into the build stage
COPY . .

# Use a lightweight Node.js image for the final stage
FROM node:alpine

WORKDIR /app

# Copy the entire project from the build stage
COPY --from=build /app/ .

# Expose the port the app runs on
EXPOSE 3000

# Start your Node.js application (replace this with your actual start command)
CMD ["npm", "run", "dev"]
